-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgXi0+4S42b9cSLm4q
xDMEbC+TZlVsBG+BdsKefpPOkyKgCgYIKoZIzj0DAQehRANCAASUXOAV3iQuQsTY
Sf3tjpSsqqVGjnEm6/GIg4Rrig8NjDQKrDBHMJfykP24Y8T3hcUnScicTzyghyiY
NneNPkfH
-----END PRIVATE KEY-----